In [1]:
import numpy as np
import lbg_forecast.sps as sps
import lbg_forecast.hyperparameters as hyp
import lbg_forecast.population_model as pop
import lbg_forecast.priors as pr
import lbg_forecast.sfh as sfh
import matplotlib.pyplot as plt

In [2]:
sps_model = sps.initialise_sps_model(neb_em=True, sfh_type=3, zcont=1, imf_type=2, dust_type=0, igm=True)

In [3]:
hyperparameter_mu_bounds, hyperparameter_sigma_max  = hyp.default_hyperparameter_bounds()
prior_parameters = hyp.sample_prior_parameters(1000, hyperparameter_mu_bounds, hyperparameter_sigma_max)

In [4]:
redshift_mass_prior_parameters = pr.setup_redshift_and_mass_priors(z_max=15)

In [5]:
sps_parameters = pop.generate_sps_parameters(1, prior_parameters[np.random.randint(0, 1000),:], redshift_mass_prior_parameters, uniform_redshift_mass=False, uniform_logf=False)
#sps_parameters[0][0] = 1e-5

In [6]:
sps.update_model(sps_model, sps_parameters[0], z_history=False, agebins=sfh.default_agebins())

In [7]:
#spec_fsps = sps.fsps_simulate_sed(sps_model)
#spec_alt = sps.get_sed(sps_model, 'lsst')

In [8]:
photo_fsps = sps.fsps_get_magnitudes(sps_model, 'lsst')
photo_alt = sps.get_magnitudes(sps_model, 'lsst')

In [9]:
photo_fsps- photo_alt

array([-0.04774747, -0.04717519, -0.04708546, -0.04746279, -0.04696231,
       -0.04273807])

In [10]:
photo_fsps

array([44.49701869, 33.22436726, 31.53748819, 31.06979602, 30.94379637,
       30.86311723])

In [11]:
photo_alt

array([44.54476616, 33.27154245, 31.58457365, 31.11725881, 30.99075868,
       30.9058553 ])

In [12]:
spec_alt = sps.get_sed(sps_model, 'lsst')

In [13]:
sps_model.wavelengths

array([9.100e+01, 9.400e+01, 9.600e+01, ..., 9.817e+07, 9.908e+07,
       1.000e+08])

In [14]:
spec_alt[1]- sps_model.wavelengths*(1+sps_parameters[0][0])

array([-3.36107997e+02, -3.47188481e+02, -3.54575470e+02, ...,
       -3.62590353e+08, -3.65951433e+08, -3.69349448e+08])